version: '3'

services:
  backend:
    build: ./backend
    command: sh -c "python3 main.py"
    ports:
      - "8000:8000"
    depends_on:
      - websocket

  websocket:
    build: ./bridge
    command: sh -c "python3 socket_server.py"
    ports:
      - "5000:5000"