version: '3'

services:
  frontend:
    build: ./frontend
    command: sh -c "npm run dev"
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend/public:/app/public

  backend:
    build: ./backend
    command: sh -c "python3 main.py"
    ports:
      - "8000:8000"
    depends_on:
      - websocket
    volumes:
      - ./frontend/public:/app/public

  websocket:
    build: ./bridge
    command: sh -c "python3 socket_server.py"
    ports:
      - "5000:5000"
